### ISSUE TITLE
No valid code signing certificate found, aborting

### ISSUE THREAD

**Issue by naveenenushan** [SignTools/ios-signer-service#103]
I cant sign ipa, got an error on ios-signer-ci on github
log is here

R```
un ./sign.sh
7
Obtaining files...
8
Creating keychain...
9
Traceback (most recent call last):
10
Cleaning up...
11
  File "/Users/runner/work/ios-signer-ci/ios-signer-ci/sign.py", line 226, in <module>
12
    run()
13
  File "/Users/runner/work/ios-signer-ci/ios-signer-ci/sign.py", line 155, in run
14
    raise Exception("No valid code signing certificate found, aborting.")
15
Exception: No valid code signing certificate found, aborting.
16
Error: Process completed with exit code 1.
```

**Expected behavior**
downloadable ipa



**System configuration**

- ios-signer-service version: v2.4.14
- Installation type: heroku
- Builder type: ios-signer-ci
- Builder version: 9201af5

**Comment by ViRb3** [comment]
Hi there. Your certificate appears to be incorrect. How did you obtain it? Please make sure you follow the guide exactly.

**Comment by naveenenushan** [comment]
Thank you, fixed
