### ISSUE TITLE
stops at obtaining files

### ISSUE THREAD

**Issue by Silfalion** [SignTools/ios-signer-service#104]
!! Please fill in this template, DO NOT ignore or delete it. !!

**I tried basic troubleshooting first**

yes

- [X ] Updated **both** [ios-signer-service](https://github.com/SignTools/ios-signer-service) **and** the builder ([ios-signer-ci](https://github.com/SignTools/ios-signer-ci) or [ios-signer-builder](https://github.com/SignTools/ios-signer-builder)) to the latest version
- [ X] Read through the [FAQ page](https://github.com/SignTools/ios-signer-service/blob/master/FAQ.md)

**Describe the bug**

when the build happens it returns this error:

```
Obtaining files...
Traceback (most recent call last):
  File "/Users/runner/work/ios-signer-ci/ios-signer-ci/util.py", line 24, in run_process
    result = subprocess.run(cmd, capture_output=capture, check=check, env=env, cwd=cwd, timeout=timeout)
  File "/usr/local/Cellar/python@3.9/3.9.6/Frameworks/Python.framework/Versions/3.9/lib/python3.9/subprocess.py", line 528, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '('curl', '-s', '-S', '-f', '-L', '-H', 'Authorization: ***', '-o', 'job.tar', '***/jobs')' returned non-zero exit status 6.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/runner/work/ios-signer-ci/ios-signer-ci/sign.py", line 211, in <module>
    curl_with_auth(secret_url + "/jobs", output=job_archive)
  File "/Users/runner/work/ios-signer-ci/ios-signer-ci/sign.py", line 27, in curl_with_auth
    return run_process(
  File "/Users/runner/work/ios-signer-ci/ios-signer-ci/util.py", line 26, in run_process
    raise (
Exception: {'stdout': '', 'stderr': 'curl: (6) Could not resolve host: ***'}
Error: Process completed with exit code 1.

```

**To reproduce**

1. Load the Delta ipa
2. wait until the build starts
3. the build fails

**Expected behavior**
App get signed

**Screenshots**

**System configuration**

- ios-signer-service version: [e.g. 2.1.1]
- Installation type: heroku
- Builder type: ios-signer-ci
- Builder version: 9201af5

**Additional context**

Selected, hopefully, both the certificate and the key.

**Comment by ViRb3** [comment]
It appears that the SERVER_URL you used cannot be resolved by the builder. Make sure that it is a publicly reachable URL, like: `https://example.herokuapp.com`.
