### ISSUE TITLE
Unable To Install "App Name.ipa"

### ISSUE THREAD

**Issue by causefx** [SignTools/ios-signer-service#13]
I get this message after trying to install an app that was successfully signed.

Unable To Install "App Name.ipa"
This app cannot be installed because its integrity could not be verified.

**Comment by ViRb3** [comment]
This usually means that the signing profile you used to sign the app is not registered with the UDID of the device where you are trying to install the signed app. Have you tested that signing profile before?

**Comment by causefx** [comment]
i just made this profile today...  here is the SS:
![image](https://user-images.githubusercontent.com/16184466/110041613-98fba500-7d01-11eb-9ce5-15445ada94a2.png)

**Comment by ViRb3** [comment]
Interesting. Which version of the service are you running? Also, what app are you trying to sign, could you share it? If you prefer, feel free to leave me a Discord or Telegram handle and I will contact you there.

**Comment by causefx** [comment]
D: CauseFX#5859

**Comment by ViRb3** [comment]
As discussed over instant messaging, the problem was resolved by updating to the latest service + CI builder version.
