### ISSUE TITLE
open data/profiles/cert.p12/names.txt: not a directory

### ISSUE THREAD

**Issue by EPiCxRIOTZZ** [SignTools/ios-signer-service#14]
i have imported my cert to the data/profiles directory and i come across this error (open data/profiles/cert.p12/names.txt: not a directory) wont let me do anything.

could you post a step by step tut on how to set it up 

thanks

**Comment by ViRb3** [comment]
You should have a folder under `data/profiles`, for an example make a folder `data/profiles/mycert`. Then inside, put your certificate (p12 file), password (pass.txt), name (name.txt) and provisioning profile (prov.mobileprovision).

**Comment by EPiCxRIOTZZ** [comment]
oh okay thank you

________________________________

**Comment by ViRb3** [comment]
No worries!
