### ISSUE TITLE
Help needed: How to setup SSL with ios signer service

### ISSUE THREAD

**Issue by URBANsUNITED** [SignTools/ios-signer-service#17]
Hi and sorry for hijacking this.

But I need help to setup the SSL way, please.
I got it working so far on my RPI3b+ and Debian Buster.
But I would like to use the direct install option.

Who can help me with is?

Reverse proxy - secure and reliable, but harder to set up

Requires publicly accessible port 443 (HTTPS)
Requires domain with valid certificate
Requires manual configuration of reverse proxy with your own authentication.
Don't protect the following endpoints:
/apps/:id/
/jobs
/jobs/:id
where :id is a wildcard parameter.

How to setup this in Debain or docker please?

Thanks a lot

URBANsUNITED

**Comment by ViRb3** [comment]
Here's some generic guides:
- https://www.digitalocean.com/community/tutorials/how-to-secure-nginx-with-let-s-encrypt-on-ubuntu-18-04
- https://www.digitalocean.com/community/tutorials/how-to-secure-nginx-with-let-s-encrypt-on-ubuntu-20-04
- https://www.digitalocean.com/community/tutorials/how-to-secure-a-containerized-node-js-application-with-nginx-let-s-encrypt-and-docker-compose

You will have to learn how to setup a HTTPS reverse proxy in general, and then try to do it with this project. Unfortunately I can't help you in more details as this is out of the scope. You can always use the ngrok setup if you can't figure this out. Good luck!
