### ISSUE TITLE
Cannot see a progress bar when uploading .ipa.

### ISSUE THREAD

**Issue by ExeRhythm** [SignTools/ios-signer-service#25]
**I tried basic troubleshooting first**
- [ ] Updated the web service **and** the builder to the latest version
- [x] Read through the FAQ: https://github.com/SignTools/ios-signer-service/blob/master/FAQ.md

**Describe the bug**
I cannot see a progress bar when uploading .ipa.

**To reproduce**
1. Upload an app

**Expected behavior**
As far as I understand, there should be a upload progress bar. You said that in #12 

**Screenshots**
<img width="498" alt="Screenshot 2021-03-15 at 14 58 57" src="https://user-images.githubusercontent.com/52459150/111150324-0085e000-859f-11eb-8f8f-c1c29ff6261c.png">

**System statistics**
- Web service version: 2.0.0
- Builder type: Github Actions
- Builder version, if applicable: 427dc08
- Deployment method: ngrok

**Comment by ViRb3** [comment]
Ah, under progress bar, I suppose you mean a 0-100% bar? I don't have that, I only added the spinning wheel. I'll update your other issue, I was meaning to add a proper progress bar anyway.
