### ISSUE TITLE
docker

### ISSUE THREAD

**Issue by dayfly** [SignTools/ios-signer-service#26]
How do I add a dockfile to the docker container?

**Comment by ViRb3** [comment]
What dockfile are you referring to? I suppose you mean a Dockerfile? If that's the case you don't need one, it is used only to build the image, which I already provide if you read the installation guide.

**Comment by dayfly** [comment]
Do I just need to apply the image?

**Comment by ViRb3** [comment]
Use the image, yes. If you don't know how to use Docker, I suggest reading that up first. You can always use the plain binaries otherwise. I'm closing this since it's not an issue specific to this project. Good luck!

**Comment by dayfly** [comment]
Thank You
