### ISSUE TITLE
404 error

### ISSUE THREAD

**Issue by dayfly** [SignTools/ios-signer-service#27]
<img width="1256" alt="스크린샷 2021-03-19 오후 4 53 01" src="https://user-images.githubusercontent.com/8287834/111748254-a43efb00-88d3-11eb-9a97-9fa420baf581.png">

I completed the ssl reverse direction, but I can't receive the cert_pass file by 404 error. Please help me.

**Comment by dayfly** [comment]
![Uploading 스크린샷 2021-03-19 오후 6.07.46.png…]()

**Comment by ViRb3** [comment]
Hello. You've shown two different errors here. In the first screenshot the builder can't reach the `$SECRET_URL/jobs` endpoint, resulting in a 404. In the second error, the file that the builder downloaded seems to be invalid - not the tar archive that it is supposed to be. From your screenshots I can't tell almost anything about your setup, so I can't help. Please create a new issue and fill in the `Bug report` template, then I will be able to help.

**Comment by dayfly** [comment]
I'll ask you one more question and post a new issue. Which pullder should I make jobs?

**Comment by ViRb3** [comment]
Could you please rephrase your question? If you're asking which builder to use, I recommend [ios-signer-ci](https://github.com/SignTools/ios-signer-ci). Check the [installation guide](https://github.com/SignTools/ios-signer-service/blob/master/INSTALL.md#1-builder) for more information and recommendations

**Comment by dayfly** [comment]
Do I have to put the jobs puller in the data puller when I use this ios-signer-service-Ci? I'm sorry to bother you so much.

**Comment by ViRb3** [comment]
No problem, you're not bothering me. I'm sorry but I can't understand what you're asking me. Could you please re-phrase your question?

**Comment by dayfly** [comment]
Should I put /jobs in the data pullder?

**Comment by ViRb3** [comment]
`/jobs` is an endpoint (part of internet address), you don't put it anywhere. It is exposed by the web service and used by the builder to download the sign files. The full URL (full internet address) is created using the `server_url` property in the configuration file. The full URL will be sent from the web service to the builder automatically. If you follow the installation guide, it should work.

**Comment by dayfly** [comment]
<img width="1191" alt="스크린샷 2021-03-20 오후 2 31 22" src="https://user-images.githubusercontent.com/8287834/111860151-fa21aa80-8988-11eb-8580-c7776e8561b1.png">

I can access the web, but CI can't access it.

**Comment by ViRb3** [comment]
Please open a new issue and fill in the template, I can't help you with so little information.

**Comment by oneday95** [comment]
It's suddenly settled. :) It runs fast in reverse direction. Thank you. :)
