### ISSUE TITLE
Sign issue

### ISSUE THREAD

**Issue by XploitKR** [SignTools/ios-signer-service#29]
**I tried basic troubleshooting first**

- [ x ] Updated **both** [ios-signer-service](https://github.com/SignTools/ios-signer-service) **and** the builder ([ios-signer-ci](https://github.com/SignTools/ios-signer-ci) or [ios-signer-builder](https://github.com/SignTools/ios-signer-builder)) to the latest version
- [ x ] Read through the [FAQ page](https://github.com/SignTools/ios-signer-service/blob/master/FAQ.md)

**Describe the bug**
Signing failed 'the codesign_allocate helper tool cannot be found or used'

**To reproduce**

upload above 90MB ipa.

**Expected behavior**

**Screenshots**

**System configuration**

- ios-signer-service version: latest
- Installation type: docker
- Builder type: both tested
- Builder version: latest

**Additional context**

**Comment by ViRb3** [comment]
Does this error only happen if you upload IPA over 90MB? Since you said `Builder type: both tested`, does this mean that the error also occurs on GitHub Actions CI?

**Comment by XploitKR** [comment]
> Does this error only happen if you upload IPA over 90MB? Since you said `Builder type: both tested`, does this mean that the error also occurs on GitHub Actions CI?

yes. only happen over 90MB.

Github Actions CI have same issue.

I think it could be a problem with the organization account.

**Comment by XploitKR** [comment]
test on gui app signer

when prompt error message

CSSMERR_TP_CERT_REVOKED
In architecture: arm64

**Comment by ViRb3** [comment]
I successfully use GitHub Actions CI with IPAs over 90MB. Having an organization account should make no difference. What GUI app signer did you test? The error you got from there seems to say that your certificate was revoked. Maybe issue a new certificate and use that instead? Can you please share the full logs from GitHub CI? A screenshot would be appreciated. This way I can see where exactly the error is happening.

**Comment by XploitKR** [comment]
i think it could be a problem with the invalid ipa.
i test on normal Youtube.ipa and modded Youtube.ipa

when modded Youtube.ipa is sign failed.
