### ISSUE TITLE
Cannot access the signing portal

### ISSUE THREAD

**Issue by saleem202** [SignTools/ios-signer-service#31]
Hi I cannot access the signing portal the following is what I get when I start the service 

Welcome to Alpine!
You can install packages with: apk add 
<package>
You may change this message by editing 
/etc/motd.
Saleem-Urs-iPhone:~# ./start-signer.sh
Starting service...
2021/03/27 19:14:25 get config: read existing: de
code: yaml: line 1: did not find expected key
ngrok by @inconshreveable            (Ctl+C to qu
it)
ngrok does not support a dynamic, color terminal 
UI on solaris.
Access the web interface for connection and tunne
l status.
Version                       2.3.35
Region                        United States (us)
Web Interface                 http://127.0.0.1:40
40
Press Ctrl+C / ^+C to stop...

**Comment by ViRb3** [comment]
```
get config: read existing: decode: yaml: line 1: did not find expected key
```
Your `signer-cfg.yml` configuration file fails to decode, so it is probably corrupt. Please delete it, let the program create a new, correct file, and fill in your changes again.

**Comment by saleem202** [comment]
Thanks Will try that and come back to you if it works

**Comment by saleem202** [comment]
Thanks that worked but when I upload the ipa after five minutes or so I get the following error 
Safari cannot open the page The error was: “cannot parse response”.

**Comment by ViRb3** [comment]
Can you please share the full logs?

**Comment by saleem202** [comment]
The following is the log

Welcome to Alpine!
You can install packages with: apk add <package>
You may change this message by editing /etc/motd.
Saleem-Urs-iPhone:~# ./start-signer.sh
Starting service...
ngrok by @inconshreveable            (Ctl+C to qu
it)
ngrok does not support a dynamic, color terminal 
UI on solaris.
Access the web interface for connection and tunne
l status.
Version                       2.3.35
Region                        United States (us)
Web Interface                 http://127.0.0.1:40
40
2021/03/28 10:38:25 ngrok public URL: https://7e8
cc0677be5.ngrok.io
Press Ctrl+C / ^+C to stop...
⇨ http server started on 127.0.0.1:8080
{"time":"2021-03-28T10:39:47.275826Z","id":"","re
mote_ip":"2a00:11c0:9:996::1:1","host":"7e8cc0677
be5.ngrok.io","method":"GET","uri":"/","user_agen
t":"Mozilla/5.0 (iPhone; CPU iPhone OS 14_3 like 
Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko
) Version/14.0.2 Mobile/15E148 Safari/604.1","sta
tus":401,"error":"code=401, message=Unauthorized"
,"latency":2767000,"latency_human":"2.767ms","byt
es_in":0,"bytes_out":27}
{"time":"2021-03-28T10:40:01.709378Z","id":"","re
mote_ip":"2a00:11c0:9:996::1:1","host":"7e8cc0677
be5.ngrok.io","method":"GET","uri":"/","user_agen
t":"Mozilla/5.0 (iPhone; CPU iPhone OS 14_3 like 
Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko
) Version/14.0.2 Mobile/15E148 Safari/604.1","sta
tus":200,"error":"","latency":166873000,"latency_
human":"166.873ms","bytes_in":0,"bytes_out":10646
}
{"time":"2021-03-28T10:40:03.013553Z","id":"","re
mote_ip":"37.252.231.114","host":"7e8cc0677be5.ng
rok.io","method":"GET","uri":"/favicon.png","user
_agent":"Mozilla/5.0 (iPhone; CPU iPhone OS 14_3 
like Mac OS X) AppleWebKit/605.1.15 (KHTML, like 
Gecko) Version/14.0.2 Mobile/15E148 Safari/604.1"
