### ISSUE TITLE
How can I contact you?

### ISSUE THREAD

**Issue by aesign** [SignTools/ios-signer-service#35]
Sorry for the off-topic, but I'd need to talk with you privately. I didn't find a way yet.

**Comment by ViRb3** [comment]
Hey, drop me a Telegram or Discord handle and I will add you. I will delete your comment immediately after to preserve your privacy.

**Comment by aesign** [comment]
Discord works: aesign#7178

**Comment by ViRb3** [comment]
It appears that your account is set up not to accept friend requests, so I can't add you.

**Comment by aesign** [comment]
Sorry, please try again.
