### ISSUE TITLE
A successfully built/signed ipa won't install

### ISSUE THREAD

**Issue by 42ism** [SignTools/ios-signer-service#36]
Hi,

I followed the instructions and currently running the web service on a Windows 10 machine with Github Actions as the builder with a developer account (provision + certificate).
The build completed successfully and the file is made available for install/download.

![image](https://user-images.githubusercontent.com/6178252/113870402-ccf23c00-977f-11eb-90d7-0782f78b1cfc.png)

But when I click the Install button nothing happens. No prompt, no install, nothing new on the iPhone's homepage.
The browsers I tried were Safari and Chrome, both the same result.

This is what I see in the web service console every time I press the Install button:
_{"time":"2021-04-07T08:51:21.8639162-04:00","id":"","remote_ip":"xx.xx.xx.xx","host":"my-private-url.trycloudflare.com","method":"GET","uri":"/apps/1df97ec4-9f61-4a58-acb9-bd4cb8293fab/manifest","user_agent":"com.apple.appstored/1.0 iOS/14.4.2 model/iPhone13,1 hwp/t8101 build/18D70 (6; dt:228) AMS/1","status":200,"error":"","latency":1394200,"latency_human":"1.3942ms","bytes_in":0,"bytes_out":1238}_

Any idea why it wouldn't install?

Thank you!

BTW I didn't mean to add the "bug" label. This could very well be a setup/user issue :) and not a "bug".

**Comment by ViRb3** [comment]
Hey there. Everything is looking good on your end. I just tried the same setup with Windows 10 and cloudflared, with both Brave and Safari, and installing works just fine on my iPhone 12 with iOS 14.4.2. I am seeing the exact same logs as well. Since you have `/apps/1df97ec4-9f61-4a58-acb9-bd4cb8293fab/manifest` and there is no error (`error":""`), then the device obtained the manifest file. Do you have any corporate policies/profiles or MDM that may prevent you from sideloading apps ad-hoc?

**Comment by ViRb3** [comment]
To verify, try uploading the signed IPA to https://www.diawi.com/ and see if you can sideload from there.

**Comment by 42ism** [comment]
@ViRb3 I can confirm I do not have any corporate policies or MDM.
I have only one other profile (that was installed by AltServer) but that one shouldn't prevent anything right? I will try to remove it and repeat the process.
There is no manifest in the folder?
![image](https://user-images.githubusercontent.com/6178252/113899721-13a15f80-979b-11eb-8fd6-e6c47273a4a0.png)
I will also try to upload and download from Diawi.

Thanks!

**Comment by 42ism** [comment]
Manifest is:

<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
    <dict>
        <key>items</key>
        <array>
            <dict>
                <key>assets</key>
                <array>
                    <dict>
                        <key>kind</key>
                        <string>software-package</string>
                        <key>url</key>
                        <string>https://my-private-url.trycloudflare.com/apps/1df97ec4-9f61-4a58-acb9-bd4cb8293fab/signed</string>
                    </dict>
                </array>
                <key>metadata</key>
                <dict>
                    <key>bundle-identifier</key>
                    <string>com.foo.bar</string>
                    <key>bundle-version</key>
                    <string>2.0</string>
                    <key>kind</key>
                    <string>software</string>
                    <key>title</key>
                    <string>CercubeNoAds(5.2.15) & YouTube(16.12.3) & iSponsorBlock(1.0-8) & YTUHD(0.0.3.7)-Qn_.ipa</string>
                </dict>
            </dict>
        </array>
    </dict>
</plist>

**Comment by 42ism** [comment]
I have some good news. I think the issue was special characters in the pre-signed ipa file. When I renamed the ipa before I uploaded it to a simple short name it installed just fine!

Thank you so much for all your hard work this project is amazing. I can finally use my developer account to sign and install ipa files wirelessly. 

Now I am going to try the iSH way to make it true portable. 

Thank you!

**Comment by ViRb3** [comment]
Ah, I suspected that this may be a problem. The ampersand (`&`) symbol has a special meaning in XML, which is the manifest's format. I will make an update to account for this.

**Comment by ViRb3** [comment]
I released an updated version, it should no longer experience this problem.

**Comment by 42ism** [comment]
Thank you so much!!!
