### ISSUE TITLE
iSH specific request: can start-signer.sh copy the trycloudflare.com URL to the clipboard 

### ISSUE THREAD

**Issue by 42ism** [SignTools/ios-signer-service#37]
Hi @ViRb3, I find it difficult to find->tap->select>copy the trycloudflare.com URL that is generated when running start-signer.sh in the output. Is it possible to either automatically copy it to the iOS clipboard or maybe make it clickable in the start-signer.sh output?

Thank you!

**Comment by ViRb3** [comment]
There doesn't seem to be a way for a script within iSH to control the clipboard, and making a link clickable is up to the terminal (in this case iSH, which doesn't seem to work). Manual selection is the only way for now unless you have any specific ideas.

**Comment by 42ism** [comment]
Thank you @ViRb3 I apologize for the delayed answer. You are correct. This can go as a request on the iSH github instead.
My iSH setup is not that stable anyways to be used with the iOS Signer web service, for some strange reason it keeps crashing during the run (while installing the signed ipa file), I suspect it is an out-of-memory issue since the entire iSH crashes and then the ipa install fails. Thank you again for this great work!

**Comment by ViRb3** [comment]
Ah yes. How big is your app? I experienced the same issue with a 260MB file. I'm not sure why it happens as the files should be streamed from disk and not stored in memory.

**Comment by 42ism** [comment]
it actually wasn't that large of a file 67 MB so I found it somewhat strange.

![image](https://user-images.githubusercontent.com/6178252/114190385-3f4a5400-9919-11eb-8a8d-e26d6faa0bea.png)

**Comment by ViRb3** [comment]
@42ism I have created a dedicated issue linked above. Let's move this conversation there.
