### ISSUE TITLE
Unable to run to get yml on Linux

### ISSUE THREAD

**Issue by VestaEldrid** [SignTools/ios-signer-service#44]
Hi I'm using Linux beta on chromebook(so arm64)
And whenever I try to run the file 
_./ios-signer-service_2.2.4_linux_arm64_
I get the error:
_-bash: ./ios-signer-service_2.2.4_linux_arm64 : Permission denied _
Need some help

**Comment by ViRb3** [comment]
You need to make the file executable first. Do this with:
```bash
chmod +x ./ios-signer-service_2.2.4_linux_arm64
```
Let me know if that fixes it for you.

**Comment by VestaEldrid** [comment]
> You need to make the file executable first. Do this with:
> 
> ```bash
> 
> chmod +x ./ios-signer-service_2.2.4_linux_arm64
> 
> ```
> 
> Let me know if that fixes it for you.


Thank you, I always forget to use chmod because I barely use Linux unless I get bored. Thanks!
