### ISSUE TITLE
Need help

### ISSUE THREAD

**Issue by luxysiv** [SignTools/ios-signer-service#45]
How to run your service on Android??? Please help me

**Comment by ViRb3** [comment]
This is not a supported use case, but it should be possible using one of the `linux` releases, for an example [ios-signer-service_2.2.4_linux_arm64](https://github.com/SignTools/ios-signer-service/releases/download/v2.2.4/ios-signer-service_2.2.4_linux_arm64). You would need to run it in [Termux](https://termux.com/) and follow the [3.2. Self-hosting on computer or server](https://github.com/SignTools/ios-signer-service/blob/master/INSTALL.md#32-self-hosting-on-computer-or-server) section. I may be able to offer limited help, so let me know if anything doesn't work.

**Comment by luxysiv** [comment]
I try to run on Termux 3 days but I can't make it work. I will try again
