### ISSUE TITLE
Apps signed but stuck afterwards

### ISSUE THREAD

**Issue by bingoxo** [SignTools/ios-signer-service#47]
Trying to run the builder on the device itself , followed all steps , when trying to install in ipa after it’s signed , ish shows : error="code=405, message=Method Not Allowed" and the ipa is stuck afterwards unable to be installed 

i think it’s better if you create a discord server/telegram channel/matrix room(most private option) where we can build a community and help each other out , meanwhile i would appreciate if i can contact you directly and help me troubleshoot this , my telegram id : REDACTED

**Comment by ViRb3** [comment]
As we spoke privately, the problem was in your signing profile. Regarding the community channel, I have been considering that, I will make sure to let you know when/if it happens.
