### ISSUE TITLE
Where do I get the "workflow key configured in your iOS Signer Service"?

### ISSUE THREAD

**Issue by ExeRhythm** [SignTools/ios-signer-service#5]

**Comment by ViRb3** [comment]
Can you please describe your problem in a bit more detail?

**Comment by ExeRhythm** [comment]
Sure, I just forked the repo (https://github.com/SignTools/ios-signer-ci) and I need to somehow obtain the "workflow key configured in your iOS Signer Service". How can I get it? Do I need to edit the signer-cfg.yml? Thanks

**Comment by ViRb3** [comment]
Ah, right. The workflow key is something that you come up with, and yes, you set it in `signer-cfg.yml`, under `workflow > key`. It will be used by the builder to talk to the service. I will update the documentation to make this more clear.

**Comment by ViRb3** [comment]
I just updated the documentation with full description of the configuration. Please check the README again.

**Comment by ExeRhythm** [comment]
Thanks!
