### ISSUE TITLE
Error: Process completed with exit code 1

### ISSUE THREAD

**Issue by isibizi** [SignTools/ios-signer-service#58]
Hello, i have an dev accout but i cant sign my apps

What is the problem?

Run ./sign.sh
Obtaining files...
Creating keychain...
Importing certificate...
1.2.840.113635.100.1.61
Signing...
Usage: xresign.sh -i APP_PATH -c CERT_NAME [-epbdas ...]

-i  path to input app to sign
-c  Common Name of signing certificate in Keychain
-e  new entitlements to use for app (Optional)
-p  path to mobile provisioning file (Optional)
-b  new bundle id (Optional)
-d  enable app debugging (get-task-allow) (Optional)
-a  force enable support for all devices (Optional)
-s  force enable file sharing through iTunes (Optional)
-n  set bundle id to mobile provisioning app id (Optional)
-w  write bundle id to file (Optional)
**Error: Process completed with exit code 1.**

**Comment by ViRb3** [comment]
Hello. What type of signing profile did you use? Provisioning profile or account username and password? How did you deploy the service? Heroku? The error probably means that something was left empty. Feel free to join the Discord if you want faster support: https://discord.gg/A4T6npnRCk

**Comment by isibizi** [comment]
I have used a prov.profile and a p12 cert from an paid dev account. I have used heroku to deploy the service.

**Comment by ViRb3** [comment]
Thanks a lot for the report. The error is almost certainly that the signer cannot find any valid code signing certificate inside your `cert.p12`. I updated the code to show more helpful error messages, you will have to re-create your `ios-signer-`ci` to get the new changes. To fix your problem, we will discuss over Discord. I will update this issue with a summary once we are done.

**Comment by ViRb3** [comment]
Please try the latest version, it includes a lot of improvements everywhere. Don't forget to update your ios-signer-ci as well if applicable.

**Comment by ViRb3** [comment]
Where do you get the error?

**Comment by isibizi** [comment]
I have the error in github under my repo in "actions"

https://ibb.co/tmrjtF5

**Comment by ViRb3** [comment]
That is not an error. It simply means that no signing jobs have been run yet.

**Comment by isibizi** [comment]
i have uploaded the ipa and the workflow runs very late ~5 min after ther upload is finshed. i dont know is this a prob of heroku or you tool ?

**Comment by ViRb3** [comment]
Most likely Github Actions is overloaded, so it takes a while to pick up your job. It happens sometimes. Let me know if the issue persists for more than a day and I'll look into it.

**Comment by ViRb3** [comment]
Assuming fixed, feel free to comment and I will re-open.
