### ISSUE TITLE
Where can I find the "cert.p12" file on my computer?

### ISSUE THREAD

**Issue by ExeRhythm** [SignTools/ios-signer-service#6]
Sorry for another issue and being stupid, but where can I find it? I tried to find it in the keychain, but if I try to export one of the certificates I have (Development), it wouldn't let me chose the .p12 option. How can I find the right certificate? Thanks!

**Comment by ExeRhythm** [comment]
Ohh, I need to export the private key, right?

**Comment by ViRb3** [comment]
You would need to export it from your keychain. Here's a few guides:
- https://help.attendify.com/en/articles/441408-how-to-export-a-distribution-certificate-as-a-p12-file
- https://stackoverflow.com/questions/33163661/os-xunable-to-export-p12-on-keychain

**Comment by ExeRhythm** [comment]
Thank you so much! :)
