### ISSUE TITLE
Getting .p12 file on Windows

### ISSUE THREAD

**Issue by bunduuk** [SignTools/ios-signer-service#62]
Seems interesting but I am stuck at "Signing profile". Sadly, I don't have a Mac, and hence I am not able to proceed without the .p12 file.

Any help in obtaining that on windows would be really appreciated.

**Comment by ViRb3** [comment]
Hello. Yes, it is quite tricky to get the .p12 file without a Mac. I am working on a solution as we speak, I will let you know when it's ready.

**Comment by ViRb3** [comment]
@bunduuk I'm happy to announce that Windows support is now officially released in v2.3.7. Read the updated guides to see how to make it work. Let me know if you have any issues and I will be glad to help.

**Comment by bunduuk** [comment]
I will try it today, thank you for the update.
