### ISSUE TITLE
Add Resign button for signed apps 

### ISSUE THREAD

**Issue by ViRb3** [SignTools/ios-signer-service#63]
Useful for free developer account apps that expire every 7 days.

**Comment by ViRb3** [comment]
Will require major change to the storage system since currently raw (even if readonly) handles to files are given away with no locking, which would make it possible to delete a file while its still being read.

**Comment by mattmuse** [comment]
This would also be fantastic when adding new UDIDs.  Unless I'm missing something I'd have to delete and re-upload all my apps again to have them signed again by the new profile after.

**Comment by ViRb3** [comment]
Added in cba83f44214513a3bc2764e9b7299b455c1673d1.
