### ISSUE TITLE
iOS 15 beta code signed apps don't work

### ISSUE THREAD

**Issue by URBANsUNITED** [SignTools/ios-signer-service#70]
Hi!

iOS 15 breaks the current code signing service. None of my signed apps work any longer.
Always says " the devoloper must update the app"

Discovered the Altstore reddit:
[https://www.reddit.com/r/AltStore/comments/numjvp/warning_ios15_breaks_altstore/](https://www.reddit.com/r/AltStore/comments/numjvp/warning_ios15_breaks_altstore/)

[https://www.reddit.com/r/AltStore/comments/nuzkng/side_loading_on_ios_15/?utm_source=share&utm_medium=web2x&context=3](https://www.reddit.com/r/AltStore/comments/nuzkng/side_loading_on_ios_15/?utm_source=share&utm_medium=web2x&context=3)

Maybe there is a fix for this fantastic workflow?!?

Thanks
URBANsUNITED

**Comment by ViRb3** [comment]
Hey there. Signing apps for iOS 15 requires macos 11.4 or above. Currently, github actions only supports macos 10. When their 11.4 image is up, signing will work:

```
https://github.com/actions/virtual-environments/issues/2486
```

**Comment by ViRb3** [comment]
Good news, macos 11 with iOS 15 signing is finally released to the general public:
```
https://github.com/actions/virtual-environments/issues/2486#issuecomment-899752373
```
Simply update your `ios-signer-ci` and signing for iOS 15 will magically work.
