### ISSUE TITLE
Configure docker

### ISSUE THREAD

**Issue by tylerwolf35** [SignTools/ios-signer-service#8]
Hello,

When you install the docker image, where is the configuration file generated in the system?

Thanks.

**Comment by ViRb3** [comment]
Just in the root, so `/signer-cfg.yml`. Thinking about it, I should probably change this behavior. I will see what I can do to make it better. For now, just mount your own config file under the root as a volume.

**Comment by tylerwolf35** [comment]
Ok, thanks.

**Comment by ViRb3** [comment]
I updated the installation instructions to reflect this.
