### ISSUE TITLE
Error 500 - no profile with id <name of ID>

### ISSUE THREAD

**Issue by kevin-ta** [SignTools/ios-signer-service#9]
Hi,

I'm trying to upload an IPA into the web interface, after a couple of seconds, the web interface redirects to `/apps` and displays `{"message":"Internal Server Error"}`.

My docker log is:
`{"time":"2021-03-04T07:18:15.894553187Z","id":"","remote_ip":"123.123.123.123","host":"https://mywebsite.ld","method":"POST","uri":"/apps","user_agent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 11_2_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.192 Safari/537.36","status":500,"error":"no profile with id 123","latency":371580849,"latency_human":"371.580849ms","bytes_in":58524658,"bytes_out":36}`.

Any better way to debug this ?

Best regards.

**Comment by ViRb3** [comment]
What was the id you gave to the profile, i.e. what was the name of the folder of the profile? While I doubt it, it could be an issue with special characters. I use plain numbers as profile IDs, like 1, 2, 3, etc. I'm going to bed now, but I'll help resolve this tomorrow. Sorry for the inconvenience.

**Comment by kevin-ta** [comment]
I used plain number like 1 as profile ID and same in name.txt.

**Comment by ViRb3** [comment]
Did you restart the service after you added/updated the profiles? The loading is not retroactive, it only happens once on start. I just created a new instance of the service from scratch (ngrok method), named my profile folder "1" and set a name.txt of "1", started the service, and the app uploads and signs just fine.

**Comment by kevin-ta** [comment]
I just redownloaded the binary and reloaded the service but still have the same error.

Here is my project structure:
`/root/data/apps`
`/root/data/profiles`
`/root/data/profiles/1`
`/root/data/profiles/1/cert.p12`
`/root/data/profiles/1/name.txt`
`/root/data/profiles/1/pass.txt`
`/root/data/profiles/1/prov.mobileprovision`
`/root/ios-signer-service-binary`
`/root/signer-cfg.yml`

name.txt only contains the string `1`.

Please find attached my reverse proxy configuration.
[nginx.txt](https://github.com/SignTools/ios-signer-service/files/6087559/nginx.txt)

Please find attached my signer-cfg.yml file:
[signer-cfg.yml.txt](https://github.com/SignTools/ios-signer-service/files/6087576/signer-cfg.yml.txt)

**Comment by ViRb3** [comment]
That is really weird. Do you have a Discord or Telegram where I could contact you for further troubleshooting?

**Comment by kevin-ta** [comment]
I just sent you an email for privacy purpose.

**Comment by ViRb3** [comment]
Please accept the friend request :)

**Comment by kevin-ta** [comment]
After investigation, this issue might be a general one on Unix system. Using a Unix text editor will auto append newline at the end of name.txt file, causing HTML to strip it as '\n' during the upload of the IPA and append it as `id + '\n'`, resulting in the service not being able to find the profile with `id`.

Thanks @ViRb3 for your time investigating this case.

**Comment by ViRb3** [comment]
Indeed, this was a very intense troubleshooting session, and the problem in the end was very simple. Go takes everything literally, so when you give it a file that ends with a newline, it will read it with the newline. However, when this same string is rendered to HTML and passed to the browser, the newline gets conveniently stripped. So when it returns, Go can no longer match it back to the original, as quite expectedly, they are not the same strings.

I reworked the IO so that all text files are stripped of spaces and newlines at write and read. That fixes this issue and hopefully any future occurances. Thanks @kevin-ta for testing so much for me!
