### ISSUE TITLE
is there any way to dump certificate from a jailbroken phone?

### ISSUE THREAD

**Issue by behradJ** [SignTools/ios-signer-service#94]
Hi 
Sorry for deleting the template I have a general question,
I'm on Linux system and just wondering is there any way to dump my altserver certificate directly from my jailbroken ios device?
I was following instructions pretty good until the signing profile section .
also thanks for your work.

**Comment by ViRb3** [comment]
Hey. It may be possible to get the certificate from ReProvision, but I have never used it so I wouldn't know. I'd recommend getting a Windows VM.
